### PR TITLE
ModuleGeneratorAntenna support (CommNetAntennasConsumptor mod)

### PR DESCRIPTION
**Pull request by yalov**

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Hmm, can you not just link the module to the ModuleGeneratorPowerHandler as your new handler does nothing differently?

**Comment by yalov** [comment]
What do you mean?
ModuleGeneratorAntennaPowerHandler does nothing differently, so I just inherited from the ModuleGeneratorPowerHandler

**Comment by yalov** [comment]
Oh, I probably could link in the config to the ModuleGeneratorPowerHandler

**Comment by yalov** [comment]
Is it OK?

**Comment by ChrisAdderley** [comment]
Yep, thanks!

**Pull request merged**
